before_install:
- sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended lmodern
script:
- mkdir _build
- DATE=`date +"%y%m%d"`
- pdflatex -jobname=Book_and_Chapter_Summary_E-mc2_$DATE -output-directory _build book_and_chapter_summary_e-mc2.tex
deploy:
  provider: releases
  api_key:
    secure: oxgAVUidPnIj4TOTL8JlcLU1K/de5L/y1u25WfxJ7vgBafmwLDRfF5v/1DCh6saIM7gQNHOHCf/+XzejfF4DtJKlCL34a7nRjHovUhVprIcq9gTdzq0Xl9o8khqLOz51yis0W7X5F8ySMuov+DupFlMG3aQjSMxznFURZHRdDizoUGVEBlN4907oJNTFh2fWiVhUPRLIR+nuGCmEuYsd8EEjWUz/2V12GxwauklCp+1ELhtXVBmMSMNvWnK1o0GUx0WvVm8p1bARCAshQjxQs6SDrQ9QitXs2ZPVDnC9K5CivE6gUfdbEJN3T3BAzFnDg2BAMLPM+6UYC3Tq4elSNMb4TON3zPaZupP8ipQ2aDLwKB5BH487rRNKr06o7NvTmlKFxx4hHua2k30ilPWV1+HtIazKjCULRn4uc35BlDKjE9pnk53LcAw6kt5l90ddx8xJor4QyF29wqRFcLD87MwWVGHBY/WPRazgpiT79uHXNANHuFsjW/4XKEOXXR8iSmkmCOtY5ffTMllYImGYvNg/T48sP62nqd+wNHmxcozAqdj/mtLO+UQoJqsObXjY8fDjJobBdgN77hO/Vmr5fGVoxeG0ug+3q/A+uekVpa5CCaEHRWE5od6IDOyIf8zjSBX92MZcQIMEHwnvMc0w2KXJtvadbbJkUuXuexWhrDU=
  file: '_build/Book_and_Chapter_Summary_E-mc2_$DATE.pdf'
  skip_cleanup: true
