before_install:
- sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended lmodern
script:
- mkdir _build
- DATE=`date +"%y%m%d"`
- pdflatex -jobname=Book_and_Chapter_Summary_E-mc2_$DATE -output-directory _build book_and_chapter_summary_e-mc2.tex
deploy:
  provider: releases
  api_key:
    secure: lsKxd9hIHxHpGUagEahH8x2YfOkrZX0KLAPxzbGTGw0d0Rcb6GklRDlzxrWFMUApZWa9rm0vLzvTEYJjreJgr67MNzpEEOi+xA3wVkDUvSAj1c6ixxLR4g9EuveglddzTFO/m/6Y8io2HKZ2AstVlUM7hdT6n/8I+hGIr4DEk2QLMFBxxhJsQod1dkB9/eNBaopnzRKuTdQ5W3xEsjCle+1v/AwTaJulZvwAfEVoYA/LeHHByfV77fQypOxj4E51kH62WZ+dbvAcfznKkiASCvxecz2cwA+I9O8Qfv7qfr8rYAcFSb49K1zbhvgMjvTEXwXh4Lzuh8pV7IV3zz//NvUL/K8pl9hSUeH43rBSQl3UumDXnyQzgvuIQjG1Vz1SbSONLJLR1koPLndas5XaPMk0rGCdSKTI/fY2t2Hm0vV+10NrclzYX2mxnmVPBMlSwv9Kn7LZ0DT4XlplT2HWRT3pWt/LhiBqmauYcPTmZW4HhBlX3m2SME3I4+k5Pr2nKEOP0doWlsVfts+IxtgKjIyyKBA8J750jF9Ht6Avsr4SxLbuyR7/87O46zIXhwYUjz6Juim+3yo+argBZRVXp8KQyUfMxucRkpSErkEMxBy9U3I7FQ3G1OHOfmt1U1u0/U+RvInBqg8NnOXcMwhCunS5j2CjSKNBV5lCON1nYaA=
  file: '_build/Book_and_Chapter_Summary_E-mc2_$DATE.pdf'
  skip_cleanup: true
